name: CI-TEST

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    name: Build and Deploy Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ajay404/ecommerce

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Generate short SHA and store it as an environment variable
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
      - name: Print inputs passed to the reusable workflow
        run: |
          echo "oops need the docker image version in this workflow step $short_sha"
